### ISSUE TITLE
Error when running yo generator-armadillo

### ISSUE THREAD

**Issue by moberlin8** [Snugug/generator-armadillo#130]
Not sure where this issue comes from. Wrong (e.g. newer) version of NPM? Missing some dependency? User error? 

`Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/me/node_modules/generator-armadillo/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)`

**Comment by Snugug** [comment]
Resolved with 3.x
