### ISSUE TITLE
Cannot find module error (v 3.0.0)

### ISSUE THREAD

**Issue by kellychurchill** [Snugug/generator-armadillo#154]
```
module.js:471
    throw err;
    ^

Error: Cannot find module '../../helpers/armadillo'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kellychurchhill/.nvm/versions/node/v6.9.2/lib/node_modules/generator-armadillo/generators/app/index.js:6:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by Snugug** [comment]
Resolved by https://github.com/Snugug/generator-armadillo/commit/0554c2db51e44f2641d8e6a4f2a670e425a22a97. Upgrade to `3.0.1`
